# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RESTAPI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	
  # Pods for RESTAPI
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'Kingfisher'
end
